<a href="https://colab.research.google.com/github/DHRUU14/Retail-Order-Analytics-Pipeline/blob/main/Retails_data_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Retail Data Project Started!")
print("Python is working in Google Colab.")

Retail Data Project Started!
Python is working in Google Colab.

In [ ]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")

FileNotFoundError: [Errno 2] No such file or directory: '/content/orders.csv'

In [ ]:
df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")

FileNotFoundError: [Errno 2] No such file or directory: '/content/orders.csv'

In [ ]:
df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd

print("Pandas is ready!")

Pandas is ready!

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'orders.csv', 'sample_data']

In [ ]:
df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [ ]:
print("Rows and columns:", df.shape)

df.head()

Rows and columns: (9994, 16)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [ ]:
df.columns.tolist()

NameError: name 'df' is not defined

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '/content/orders.csv'

In [ ]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower().endswith(".csv"):
            print(os.path.join(root, file))

/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_train.csv

In [ ]:
import pandas as pd

df = pd.read_csv("/content/orders.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

Dataset loaded successfully!
Rows and columns: (9994, 16)

In [ ]:
df.columns.tolist()

['Order Id',
 'Order Date',
 'Ship Mode',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub Category',
 'Product Id',
 'cost price',
 'List Price',
 'Quantity',
 'Discount Percent']

In [ ]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 9994
Number of columns: 16

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   object
 2   Ship Mode         9993 non-null   object
 3   Segment           9994 non-null   object
 4   Country           9994 non-null   object
 5   City              9994 non-null   object
 6   State             9994 non-null   object
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   object
 9   Category          9994 non-null   object
 10  Sub Category      9994 non-null   object
 11  Product Id        9994 non-null   object
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), object(10)
memory usage: 1.2+ MB

In [ ]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Order Id,9994.0,NaN,NaN,NaN,4997.5,2885.163629,1.0,2499.25,4997.5,7495.75,9994.0
Order Date,9994,730,2023-03-09,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ship Mode,9993,6,Standard Class,5962,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Segment,9994,3,Consumer,5191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,9994,1,United States,9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,9994,531,New York City,915,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,9994,49,California,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Postal Code,9994.0,NaN,NaN,NaN,55190.379428,32063.69335,1040.0,23223.0,56430.5,90008.0,99301.0
Region,9994,4,West,3203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,9994,3,Office Supplies,6026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub Category,9994,17,Binders,1523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Id,9994,1862,OFF-PA-10001970,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cost price,9994.0,NaN,NaN,NaN,201.189714,537.743203,0.0,20.0,50.0,180.0,18110.0
List Price,9994.0,NaN,NaN,NaN,229.756854,623.245839,0.0,20.0,50.0,210.0,22640.0
Quantity,9994.0,NaN,NaN,NaN,3.789574,2.22511,1.0,2.0,3.0,5.0,14.0
Discount Percent,9994.0,NaN,NaN,NaN,3.48409,1.114211,2.0,2.0,3.0,4.0,5.0

In [ ]:
missing = df.isnull().sum()

print("Missing values by column:")
print(missing[missing > 0])

Missing values by column:
Ship Mode    1
dtype: int64

In [ ]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_summary[missing_summary["Missing Count"] > 0]

           Missing Count  Missing Percentage
Ship Mode              1                0.01

In [ ]:
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 0

In [ ]:
print("Duplicate Order IDs:", df["Order Id"].duplicated().sum())

Duplicate Order IDs: 0

In [ ]:
# Find common placeholder values in text columns

text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    values = df[col].astype("string").str.strip().str.lower()
    mask = values.isin([
        "unknown",
        "not available",
        "n/a",
        "na",
        "none",
        "null"
    ])

    if mask.any():
        print(f"\nColumn: {col}")
        print(values[mask].value_counts())

Column: Ship Mode
Ship Mode
not available    4
unknown          1
Name: count, dtype: Int64

In [ ]:
price_columns = ["cost price", "List Price"]

for col in price_columns:
    print(f"\n{col}")
    print("Zero values:", (df[col] == 0).sum())
    print("Negative values:", (df[col] < 0).sum())

cost price
Zero values: 507
Negative values: 0

List Price
Zero values: 507
Negative values: 0

In [ ]:
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative quantities:", (df["Quantity"] < 0).sum())

print("\nDiscount percentage values:")
print(df["Discount Percent"].value_counts().sort_index())

Zero quantities: 0
Negative quantities: 0

Discount percentage values:
Discount Percent
2    2523
3    2542
4    2497
5    2432
Name: count, dtype: int64

In [ ]:
print("First 10 order dates:")
print(df["Order Date"].head(10).to_list())

print("\nDate column data type:")
print(df["Order Date"].dtype)

First 10 order dates:
['2023-03-01', '2023-08-15', '2023-01-10', '2022-06-18', '2022-07-13', '2022-03-13', '2022-12-28', '2022-01-25', '2023-03-23', '2023-05-16']

Date column data type:
object

In [ ]:
zero_cost = df["cost price"] == 0
zero_list = df["List Price"] == 0

print("Both prices are zero:", (zero_cost & zero_list).sum())
print("Only cost price is zero:", (zero_cost & ~zero_list).sum())
print("Only list price is zero:", (~zero_cost & zero_list).sum())

Both prices are zero: 507
Only cost price is zero: 0
Only list price is zero: 0

In [ ]:
df.loc[
    zero_cost | zero_list,
    ["Order Id", "Order Date", "Product Id",
     "cost price", "List Price", "Quantity", "Discount Percent"]
].head(15)

,Order Id,Order Date,Product Id,cost price,List Price,Quantity,Discount Percent
15,16,2022-06-18,OFF-BI-10000756,0,0,3,5
30,31,2022-11-20,OFF-EN-10001509,0,0,2,5
61,62,2023-04-08,OFF-AR-10001868,0,0,1,5
70,71,2022-11-29,OFF-BI-10004654,0,0,1,3
75,76,2023-04-17,OFF-BI-10004182,0,0,3,4
101,102,2022-07-25,OFF-BI-10002609,0,0,3,3
108,109,2023-10-12,OFF-AR-10000390,0,0,1,3
114,115,2023-11-08,OFF-EN-10002600,0,0,2,4
126,127,2022-07-14,OFF-BI-10003274,0,0,2,4
136,137,2022-03-28,OFF-FA-10002988,0,0,2,5
179,180,2022-03-08,OFF-AR-10001940,0,0,1,5
198,199,2022-12-21,OFF-BI-10000343,0,0,2,5
202,203,2022-12-31,OFF-AP-10003622,0,0,1,5
225,226,2023-11-18,OFF-AR-10001026,0,0,1,2
242,243,2022-11-08,FUR-FU-10002505,0,0,3,4

In [ ]:
print(df["Ship Mode"].value_counts(dropna=False))

Ship Mode
Standard Class    5962
Second Class      1945
First Class       1538
Same Day           543
Not Available        4
unknown              1
NaN                  1
Name: count, dtype: int64

In [ ]:
dates = pd.to_datetime(
    df["Order Date"],
    format="%Y-%m-%d",
    errors="coerce"
)

print("Dates that failed validation:", dates.isna().sum())
print("Earliest order date:", dates.min())
print("Latest order date:", dates.max())

Dates that failed validation: 0
Earliest order date: 2022-01-01 00:00:00
Latest order date: 2023-12-31 00:00:00

In [ ]:
zero_price_rows = df[
    (df["cost price"] == 0) &
    (df["List Price"] == 0)
]

print("Zero-price records:", len(zero_price_rows))
print("Unique products in these records:",
      zero_price_rows["Product Id"].nunique())

zero_price_rows[
    ["Product Id", "Category", "Sub Category",
     "cost price", "List Price"]
].head(10)

Zero-price records: 507
Unique products in these records: 264

          Product Id         Category Sub Category  cost price  List Price
15   OFF-BI-10000756  Office Supplies      Binders           0           0
30   OFF-EN-10001509  Office Supplies    Envelopes           0           0
61   OFF-AR-10001868  Office Supplies          Art           0           0
70   OFF-BI-10004654  Office Supplies      Binders           0           0
75   OFF-BI-10004182  Office Supplies      Binders           0           0
101  OFF-BI-10002609  Office Supplies      Binders           0           0
108  OFF-AR-10000390  Office Supplies          Art           0           0
114  OFF-EN-10002600  Office Supplies    Envelopes           0           0
126  OFF-BI-10003274  Office Supplies      Binders           0           0
136  OFF-FA-10002988  Office Supplies    Fasteners           0           0

In [ ]:
zero_product_ids = zero_price_rows["Product Id"].unique()

other_records = df[
    df["Product Id"].isin(zero_product_ids) &
    ((df["cost price"] > 0) | (df["List Price"] > 0))
]

print("Records with nonzero prices for these products:",
      len(other_records))

other_records[
    ["Product Id", "cost price", "List Price"]
].head(10)

Records with nonzero prices for these products: 1160

          Product Id  cost price  List Price
6    OFF-AR-10002833          10          10
8    OFF-BI-10003910          20          20
25   OFF-BI-10001634          10          10
32   OFF-BI-10001525          10          10
51   FUR-FU-10001706          10          10
53   OFF-FA-10000304          20          20
63   OFF-BI-10001078          20          30
81   OFF-AR-10002053          10          10
87   OFF-LA-10000134          10          10
112  OFF-BI-10003981          30          30

In [ ]:
# Select one product that has zero prices
sample_product = zero_price_rows["Product Id"].iloc[0]

# Show all records for that product
df[df["Product Id"] == sample_product][
    ["Order Id", "Order Date", "Product Id",
     "cost price", "List Price", "Quantity",
     "Discount Percent"]
]

,Order Id,Order Date,Product Id,cost price,List Price,Quantity,Discount Percent
15,16,2022-06-18,OFF-BI-10000756,0,0,3,5
2300,2301,2022-07-13,OFF-BI-10000756,10,10,3,2
2880,2881,2023-06-28,OFF-BI-10000756,30,30,6,2
3506,3507,2022-08-04,OFF-BI-10000756,0,0,4,5
4180,4181,2022-12-25,OFF-BI-10000756,0,0,5,4
4541,4542,2022-11-22,OFF-BI-10000756,10,10,7,3
8765,8766,2022-11-09,OFF-BI-10000756,0,0,2,3
9492,9493,2023-04-29,OFF-BI-10000756,30,40,9,3

In [ ]:
df["zero_price_flag"] = (
    (df["cost price"] == 0) &
    (df["List Price"] == 0)
)

print("Flagged records:", df["zero_price_flag"].sum())
print("Original rows preserved:", len(df))

Flagged records: 507
Original rows preserved: 9994

In [ ]:
# Create a separate working copy
df_work = df.copy()

print("Original dataset rows:", len(df))
print("Working dataset rows:", len(df_work))
print("Working dataset columns:", len(df_work.columns))

Original dataset rows: 9994
Working dataset rows: 9994
Working dataset columns: 17

In [ ]:

# STEP 13: Clean and validate the working dataset

# 1. Create a clean working copy
df_clean = df_work.copy()

# 2. Preserve the original shipping values for auditing
df_clean["Ship Mode Original"] = df_clean["Ship Mode"]

# Standardize text for checking placeholders
ship_text = df_clean["Ship Mode"].astype("string").str.strip()

invalid_ship = (
    ship_text.isna()
    | ship_text.str.lower().isin(["not available", "unknown", ""])
)

# We don't know the correct shipping method, so use a proper missing value
df_clean.loc[invalid_ship, "Ship Mode"] = pd.NA

# 3. Convert order dates to a proper datetime type
df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    format="%Y-%m-%d",
    errors="coerce"
)

# 4. Treat postal codes as identifiers rather than measurements
df_clean["Postal Code"] = df_clean["Postal Code"].astype("string")

# 5. Generate a data-quality report
print("========== CLEANING REPORT ==========")
print("Original rows:", len(df))
print("Cleaned working rows:", len(df_clean))
print("Original columns:", len(df.columns))
print("Cleaned columns:", len(df_clean.columns))

print("\nMissing values in cleaned shipping method:")
print(df_clean["Ship Mode"].isna().sum())

print("\nInvalid dates:", df_clean["Order Date"].isna().sum())
print("Postal Code data type:", df_clean["Postal Code"].dtype)
print("Order Date data type:", df_clean["Order Date"].dtype)

print("\nZero-price records flagged:", df_clean["zero_price_flag"].sum())
print("Exact duplicate rows:", df_clean.duplicated().sum())

print("\nCleaned dataset preview:")
display(df_clean.head())

========== CLEANING REPORT ==========
Original rows: 9994
Cleaned working rows: 9994
Original columns: 17
Cleaned columns: 18

Missing values in cleaned shipping method:
6

Invalid dates: 0
Postal Code data type: string
Order Date data type: datetime64[ns]

Zero-price records flagged: 507
Exact duplicate rows: 0

Cleaned dataset preview:

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent,zero_price_flag,Ship Mode Original
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,False,Second Class
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,False,Second Class
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,False,Second Class
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,False,Standard Class
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,False,Standard Class

In [ ]:

import pandas as pd

# STEP 14A: Build a data-quality report
quality_report = pd.DataFrame({
    "Column": df_clean.columns,
    "Data Type": [str(dtype) for dtype in df_clean.dtypes],
    "Missing Values": df_clean.isna().sum().values,
    "Unique Values": df_clean.nunique().values
})

print("========== DATA QUALITY REPORT ==========")
display(quality_report)

# STEP 14B: Validate the dataset
print("\n========== VALIDATION ==========")
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))
print("Duplicate rows:", df_clean.duplicated().sum())
print("Missing shipping methods:", df_clean["Ship Mode"].isna().sum())
print("Invalid dates:", df_clean["Order Date"].isna().sum())
print("Flagged zero-price rows:", df_clean["zero_price_flag"].sum())

# STEP 14C: Save the cleaned dataset
df_clean.to_csv("/content/retail_orders_cleaned.csv", index=False)

# Save the quality report separately
quality_report.to_csv("/content/data_quality_report.csv", index=False)

print("\nFiles created:")
print("/content/retail_orders_cleaned.csv")
print("/content/data_quality_report.csv")

========== DATA QUALITY REPORT ==========

                Column       Data Type  Missing Values  Unique Values
0             Order Id           int64               0           9994
1           Order Date  datetime64[ns]               0            730
2            Ship Mode          object               6              4
3              Segment          object               0              3
4              Country          object               0              1
5                 City          object               0            531
6                State          object               0             49
7          Postal Code          string               0            631
8               Region          object               0              4
9             Category          object               0              3
10        Sub Category          object               0             17
11          Product Id          object               0           1862
12          cost price           int64               0            280
13          List Price           int64               0            289
14            Quantity           int64               0             14
15    Discount Percent           int64               0              4
16     zero_price_flag            bool               0              2
17  Ship Mode Original          object               1              6

========== VALIDATION ==========
Rows: 9994
Columns: 18
Duplicate rows: 0
Missing shipping methods: 6
Invalid dates: 0
Flagged zero-price rows: 507

Files created:
/content/retail_orders_cleaned.csv
/content/data_quality_report.csv